In [33]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv(r"C:\Users\Carlo\Repos\TrainingsTool\Tennis\Datasets\charting-m-points-from-2017-new.csv", encoding="unicode_escape", low_memory=False )

In [16]:
df_1 = df.loc[:, ["1st", "2nd"]]
df_1_test = df_1.head(20)

In [17]:
len(df_1), len(df_1_test)

(295353, 20)

In [89]:
df_1 = df_1.astype({"1st": str, "2nd": str})
# join the two ralley colums together into one column with "," seperator
df_1["1st,2nd"] = df_1[["1st", "2nd"]].apply(lambda x: ",".join(x), axis=1)
df_1.drop(["1st", "2nd"], axis = 1, inplace=True)

In [90]:
df_1

                 1st,2nd
0                  4d,5n
1                 4#,nan
2            4n,5f29f3n#
3              6f3x#,nan
4                 4#,nan
...                  ...
295348  4b1b1f1b1f1*,nan
295349      6w,5f1b2b3d@
295350             4w,6d
295351     6s1f1f2n#,nan
295352         6s2n#,nan

[295353 rows x 1 columns]

In [155]:
df_1_0_10000 = df_1[0:10001]
df_1_10001_20000 = df_1[10001:20001]
df_1_20001_30000 = df_1[20001:30001]
df_1_30001_40000 = df_1[30001:40001]
df_1_40001_50000 = df_1[40001:50001]
df_1_50001_60000 = df_1[50001:60001]
df_1_60001_70000 = df_1[60001:70001]
df_1_70001_80000 = df_1[70001:80001]
df_1_80001_90000 = df_1[80001:90001]
df_1_90001_100000 = df_1[90001:100001]
df_1_100001_110000 = df_1[100001:110001]
df_1_110001_120000 = df_1[110001:120001]
df_1_120001_130000 = df_1[120001:130001]
df_1_130001_140000 = df_1[130001:140001]
df_1_140001_150000 = df_1[140001:150001]
df_1_150001_160000 = df_1[150001:160001]
df_1_160001_170000 = df_1[160001:170001]
df_1_170001_180000 = df_1[170001:180001]
df_1_180001_190000 = df_1[180001:190001]
df_1_190001_200000 = df_1[190001:200001]
df_1_200001_210000 = df_1[200001:210001]
df_1_210001_220000 = df_1[210001:220001]
df_1_220001_230000 = df_1[220001:230001]
df_1_230001_240000 = df_1[230001:240001]
df_1_240001_250000 = df_1[240001:250001]
df_1_250001_260000 = df_1[250001:260001]
df_1_260001_270000 = df_1[260001:270001]
df_1_270001_280000 = df_1[270001:280001]
df_1_280001_290000 = df_1[280001:290001]
df_1_290001_295353 = df_1[290001:295353]

In [156]:
#df_6000_test = df_1.head(1000)
df_test = df_1_10001_20000

In [157]:
df_1_test_test = df_test["1st,2nd"]

In [158]:
shot_list_dataframe = pd.DataFrame()
for i in range(1):
    shot_list_dataframe["shot_"+str(i)] = np.nan

In [159]:
possible_shots = ["f", "b", "r", "s", "v", "z", "o", "p", "y", "l", "m", "h", "i", "j", "k", "t", "u"]
second_serve = ","
len_of_longest_ralley = 0
k = 0
# i is a ralley
for i in df_1_test_test:
    # Initializeing new shot for each new ralley
    shot = ""
    shot_list = []
    # every char in each ralley will be looked at
    for char in range(0, len(i)):
        # if the char is not in the possible_shots list, the char is 
        # appended to the current shot
        if i[char] not in possible_shots and i[char] != second_serve:
            shot = shot + str(i[char])
        # if the char is the ",", shot is done and appended to the 
        # shot_list
        elif i[char] == second_serve:
            shot = shot + second_serve
            shot_list.append(shot)
            shot = ""
        # in all other cases, shot is done and appended to the shot_list
        else:
            shot_list.append(shot)
            shot = str(i[char])
    # the last shot has to be appended here, because it is not going 
    # into the loop again
    shot_list.append(shot)

    # if the last element of the shot list is "nan" we delete that 
    # because we dont want wo predict "nan" and also the "," from the 
    # last shot
    if shot_list[-1] == "nan":
        shot_list.pop()
    if shot_list[-1][-1] == "," and len(shot_list) > 1:
        shot_list[-1] = shot_list[-1].rstrip(shot_list[-1][-1])
    
    # finding the longest shot_list/ralley in the dataset
    if len(shot_list) > len_of_longest_ralley:
        len_of_longest_ralley = len(shot_list)

    shot_list_series = pd.Series(shot_list)
    shot_list_small_df = pd.DataFrame(shot_list)
    #print(shot_list)
    # now the shot list is beautiful and can add it to the empyt shot_list_dataframe
    #shot_list_dataframe.loc[len(shot_list_dataframe)] = pd.Series(shot_list)
    #pd.concat([shot_list_dataframe, pd.Series([shot_list])], ignore_index=True)
    #df = shot_list_dataframe.append(shot_list_series, ignore_index=True)
    #shot_list_dataframe["ralley_" + str(k)] = pd.Series(shot_list)
    #k = k + 1
    shot_list_dataframe = pd.concat([shot_list_dataframe, shot_list_small_df], ignore_index=True, axis=1)

In [160]:
shot_list_dataframe

,0,1,2,3,4,5,6,7,8,9,...,9991,9992,9993,9994,9995,9996,9997,9998,9999,10000
0,NaN,"6n,","6n,",6,6,"4*,",5,6,"6*,",6,...,6,"4n,","5d,","4n,","5d,",4+,6,6,"6w,","4d,"
1,NaN,5,5,f27,s38,NaN,f28,f37,NaN,s28,...,f18,5,5,4,5d,b38w#,s27,f2d#,6,4+
2,NaN,b18,f29,f39w@,f39*,NaN,f1n@,f+39,NaN,f18,...,s18,f29,f39,b29,NaN,NaN,f+18,NaN,b37,b1
3,NaN,f28,b38,NaN,NaN,NaN,NaN,b2n#,NaN,f39w#,...,f19,f29,b2n#,f37,NaN,NaN,b1,NaN,f18,v37*
4,NaN,f28,f38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,b2d@,f29,NaN,f38,NaN,NaN,v37*,NaN,b18,NaN
5,NaN,f18,b29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,f28,NaN,b39,NaN,NaN,NaN,NaN,f17,NaN
6,NaN,f18,f;29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,f29,NaN,f38,NaN,NaN,NaN,NaN,f+38,NaN
7,NaN,f39,f37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,b28,NaN,b38,NaN,NaN,NaN,NaN,m3,NaN
8,NaN,s39,f38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,s+29,NaN,f38,NaN,NaN,NaN,NaN,o19*,NaN
9,NaN,f37,b37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,b38*,NaN,b3d@,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,s29,s18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,f38,f19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,b28,f28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,f17,b29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,r18,s17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,f+39,r+28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,m1#,l29*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
shot_list_dataframe_T = shot_list_dataframe.transpose()

In [151]:
shot_list_dataframe_T

,0,1,2,3,4,5,6,7,8,9,...,37,38,39,40,41,42,43,44,45,46
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"4d,",5n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"4#,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"4n,",5,f29,f3n#,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,f3x#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14996,5,b28,f3,b3,f2,f2,f3,b3,s3,s3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14997,4,f29,f3n#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14998,5,f39w#,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14999,"6n,",4,f19,f3d#,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15000,"6n,",4,b3d@,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN